Feature/add reducers and actions
nxn404-n/bookstore pull request #2
Opened 2023-04-14 19:09 UTC by nxn404-n

## In this branch

- Added react toolkit
- Added slices

2023-04-14 19:36 UTC, emmiiorji requested changes
Hi @nxn404-n, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220869680-787a77f7-922b-4e57-8fa4-368533d83b89.gif'/>
</div>

## Good Highlights✔️

- The structure of the files follow the duck's pattern
- The reducer was well created with configureStore
- The actions look good


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-14 19:36 UTC, emmiiorji commented on src/redux/books/booksSlice.js
> +export const { addBook } = booksSlice.actions;
Well done for creating the actions for adding and removing books. You seemed to miss out on adding the removeBook action in your export. Kindly include it.

2023-04-14 19:36 UTC, emmiiorji commented on src/redux/categories/categoriesSlice.js
> +export const { addCategory } = categoriesSlice.actions;
You created the `checkStatus` action but exported `addCategory`.  This will lead to error, kindly reconcile the names.

2023-04-14 21:38 UTC, rotimiazeez approved these changes
Hi @nxn404-n  👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job implementing the required changes 👍🏽 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-15 09:15 UTC, merged

2023-07-20 21:29 UTC, prolajumokeoni reviewed
Hi @nxn404-n 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- Created  book's actions and reducer ✅ 
 - Installed and used  Redux Toolkit 👍🏿 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._